# Generated by Django 4.2.16 on 2026-01-26 02:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='修改時間')),
                ('name', models.CharField(help_text='商品名稱', max_length=200)),
                ('required_points', models.IntegerField(help_text='兌換所需點數，不得為負數', validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.IntegerField(default=0, help_text='庫存數量，不得為負數', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='上架狀態，True=上架, False=下架（軟刪除）')),
                ('memo', models.CharField(blank=True, help_text='商品備註', max_length=300, null=True)),
                ('store', models.ForeignKey(help_text='所屬店家', on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'is_active'], name='products_store_i_7e53ff_idx'), models.Index(fields=['is_active'], name='products_is_acti_cb485f_idx')],
            },
        ),
    ]
