# Generated by Django 4.2.16 on 2026-01-26 08:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='修改時間')),
                ('amount', models.IntegerField(help_text='異動點數（儲值為正數，兌換為負數）')),
                ('tx_type', models.CharField(choices=[('DEPOSIT', '儲值'), ('REDEMPTION', '兌換')], help_text='交易類型：DEPOSIT=儲值, REDEMPTION=兌換', max_length=20)),
                ('is_success', models.BooleanField(default=True, help_text='交易狀態，True=成功, False=失敗')),
                ('balance_after', models.IntegerField(help_text='異動後餘額，用於後續對帳審核', validators=[django.core.validators.MinValueValidator(0)])),
                ('memo', models.CharField(blank=True, help_text='備註', max_length=300, null=True)),
                ('user', models.ForeignKey(help_text='所屬用戶', on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '點數交易紀錄',
                'verbose_name_plural': '點數交易紀錄',
                'db_table': 'point_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'tx_type'], name='point_trans_user_id_868dd7_idx'), models.Index(fields=['user', 'created_at'], name='point_trans_user_id_7622fc_idx'), models.Index(fields=['is_success'], name='point_trans_is_succ_68bc22_idx')],
            },
        ),
    ]
