# Generated by Django 4.2.16 on 2026-01-27 01:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_alter_product_store'),
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='修改時間')),
                ('exchange_code', models.CharField(help_text='交換序號，用於店家核銷（格式：EX + 日期 + 隨機碼）', max_length=20, unique=True)),
                ('points_spent', models.IntegerField(help_text='消費點數，紀錄當時交換的點數價格', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('PENDING', '待核銷'), ('VERIFIED', '已核銷')], default='PENDING', help_text='交換狀態：PENDING=待核銷, VERIFIED=已核銷', max_length=20)),
                ('product', models.ForeignKey(help_text='兌換商品', on_delete=django.db.models.deletion.PROTECT, related_name='exchanges', to='products.product')),
                ('user', models.ForeignKey(help_text='兌換會員', on_delete=django.db.models.deletion.CASCADE, related_name='point_exchanges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '點數兌換紀錄',
                'verbose_name_plural': '點數兌換紀錄',
                'db_table': 'point_exchanges',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='point_excha_user_id_2ebcd9_idx'), models.Index(fields=['product', 'status'], name='point_excha_product_504508_idx'), models.Index(fields=['exchange_code'], name='point_excha_exchang_8476b3_idx'), models.Index(fields=['status'], name='point_excha_status_556d60_idx')],
            },
        ),
    ]
