# Generated by Django 4.2.16 on 2026-01-27 02:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_pointexchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointexchange',
            name='quantity',
            field=models.IntegerField(default=1, help_text='兌換數量（1-5）', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='pointexchange',
            name='points_spent',
            field=models.IntegerField(help_text='消費點數，紀錄當時交換的點數價格（required_points * quantity）', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
