# Generated by Django 4.2.16 on 2026-01-23 08:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='修改時間')),
                ('balance', models.IntegerField(default=0, help_text='點數餘額，不得為負數', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_locked', models.BooleanField(default=False, help_text='錢包鎖定狀態，True=鎖定（禁止交易）, False=正常')),
                ('user', models.OneToOneField(help_text='所屬用戶', on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '使用者點數',
                'verbose_name_plural': '使用者點數',
                'db_table': 'user_points',
                'ordering': ['-created_at'],
            },
        ),
    ]
